#!/bin/bash
declare -A cor=( [0]="\033[1;37m" [1]="\033[1;34m" [2]="\033[1;31m" [3]="\033[1;33m" [4]="\033[1;32m" )
barra="\033[0m\e[34m======================================================\033[1;37m"
SCPdir="/etc/newadm" && [[ ! -d ${SCPdir} ]] && exit 1
SCPfrm="/etc/ger-frm" && [[ ! -d ${SCPfrm} ]] && exit
SCPinst="/etc/ger-inst" && [[ ! -d ${SCPinst} ]] && exit
SCPidioma="${SCPdir}/idioma" && [[ ! -e ${SCPidioma} ]] && touch ${SCPidioma}

#Repositorio-GITHUB
link_bin="https://raw.githubusercontent.com/AAAAAEXQOSyIpN2JZ0ehUQ/ADM-ULTIMATE-NEW-FREE/master/Install/blockt"
[[ ! -e /bin/blockt ]] && wget -O /bin/blockt ${link_bin} > /dev/null 2>&1 && chmod +x /bin/blockt

[[ -e /etc/Plus-torrent ]] && torrent=$(echo -e "\033[1;32mon ") || torrent=$(echo -e "\033[1;31moff ")

fun_blockt () {
/bin/blockt
}

msg -ama "$(fun_trans "FIREWALL BLOQUEIO TORRENT") ${cor[4]}[NEW-ADM]"
msg -bar
echo -ne "\033[1;32m [1] > " && msg -azu "$(fun_trans "PLUS-TORRENT") $torrent"
echo -ne "\033[1;32m [0] > " && msg -bra "$(fun_trans "VOLTAR")"
msg -bar
while [[ ${arquivoonlineadm} != @(0|[1-1]) ]]; do
read -p "[0-1]: " arquivoonlineadm
tput cuu1 && tput dl1
done
case $arquivoonlineadm in
0)exit;;
1)fun_blockt;;
esac
msg -bar