#!/bin/bash
source cabecalho

echo -e "${cor[1]} =================================== ${cor[0]}"
echo -e "${cor[2]} ∆ ${cor[5]} ${txt[4]}"
echo -e "${cor[1]} =================================== ${cor[0]}"
echo -e "${cor[2]} |0|•${cor[4]} ${txt[13]}"
echo -e "${cor[2]} |1|•${cor[3]} ${txt[5]}"
echo -e "${cor[2]} |2|•${cor[3]} ${txt[6]}"
echo -e "${cor[2]} |3|•${cor[3]} ${txt[7]}"
echo -e "${cor[2]} |4|•${cor[4]} ${txt[8]}"
echo -e "${cor[2]} |5|•${cor[3]} ${txt[12]}"
echo -e "${cor[2]} |6|•${cor[3]} ${txt[20]} $VERIFICAR_PID"
echo -e "${cor[2]} |7|•${cor[3]} ${txt[26]}"
echo -e "${cor[2]} |8|•${cor[3]} ${txt[256]}"
echo -e "${cor[2]} |9|•${cor[3]} ${txt[290]} ${bot}"
echo -e "${cor[2]} |10|•${cor[3]} ${txt[291]}"
echo -e "${cor[1]} =================================== ${cor[0]}"