#!/bin/bash
source menu-txt
echo -ne "${cor[6]}"
read -p " ${txt[9]} " _selecao
case $_selecao in
0)
clear
echo -e "${cor[0]}"
exit
;;
1)
clear
source user
exit
;;
2)
clear
source ferramentas
exit
;;
3)
fun_atualizar
exit
;;
4)
remover_adm
exit
;;
5)
funcao_cores
source menu
exit
;;
6)
funcao_verificacao > /dev/null 2>&1
source menu
exit
;;
7)
funcao_idioma
source menu
exit
;;
8)
proxy_soks
source menu
exit
;;
9)
if [ "$(ps x | grep "ultimatebot" | grep -v "grep")" = "" ]; then
echo -e "${cor[1]} =================================== ${cor[5]}"
read -p " TELEGRAN BOT TOKEN: " tokenxx
read -p " TELEGRAN BOT LOGUIN: " loguin
read -p " TELEGRAN BOT PASS: " pass
echo -e "${cor[1]} =================================== ${cor[0]}"
echo "${loguin}:${pass}" > ./bottokens
screen -dmS screen bash ./ultimatebot "$tokenxx" > /dev/null 2>&1
echo -e " BOT STARTED"
echo -e "${cor[1]} =================================== ${cor[0]}"
else
kill -9 $(ps x | grep "ultimatebot" | grep -v "grep" | awk '{print $1}')
[[ -e ./bottokens ]] && rm ./bottokens
echo -e "${cor[1]} =================================== ${cor[5]}"
echo -e " BOT STOPED"
echo -e "${cor[1]} =================================== ${cor[0]}"
fi
sleep 4s
source menu
;;
10)
source SSL
exita
;;
*)
source menu
;;
esac