#!/bin/bash





if [ -d  /root/.vnc/ ];then
vnc=$(ls /root/.vnc/ | grep :1.pid)
else
vnc=""
fi
if [ "$vnc" = "" ]; then





if [[ "$resposta" = '1' ]]; then


apt-get install xfce4 xfce4-goodies gnome-icon-theme tightvncserver
apt-get install iceweasel


echo -e "\033[1;34m ESCOLHA UMA SENHA e DEPOIS CONFIRMA\033[1;32m"

vncserver
apt-get install firefox -y

clear
echo -e "VNC se conecta usando o ip da vps na porta 5901"
echo -e "Exemplo: $AIP:5901\033[1;32m"
echo -e "Para acessar a interface gráfica"
echo -e "\Baixe na PlayStore o VNC VIWER"
echo -e "Coloque o Ip $AIP e a porta 5901"
read -p "enter"

elif [[ "$resposta" = '2' ]]; then
if [ "$vnc" = "" ]; then
vncserver
else
vncserver -kill :1
fi

elif [[ "$resposta" = '3' ]]; then
apt-get purge xfce4 xfce4-goodies gnome-icon-theme tightvncserver -y
apt-get purge iceweasel -y
apt-get purge firefox -y
vncserver -kill :1
vncserver -kill :2
vncserver -kill :3
fi