#!/bin/bash
declare -A cor=( [0]="\033[1;37m" [1]="\033[1;34m" [2]="\033[1;31m" [3]="\033[1;33m" [4]="\033[1;32m" )
barra="\033[0m\e[34m======================================================\033[1;37m"
SCPdir="/etc/newadm" && [[ ! -d ${SCPdir} ]] && exit
SCPfrm="/etc/ger-frm" && [[ ! -d ${SCPfrm} ]] && exit
SCPinst="/etc/ger-inst" && [[ ! -d ${SCPinst} ]] && exit

fun_trans () { 
local texto
local retorno
declare -A texto
SCPidioma="${SCPdir}/idioma"
[[ ! -e ${SCPidioma} ]] && touch ${SCPidioma}
local LINGUAGE=$(cat ${SCPidioma})
[[ -z $LINGUAGE ]] && LINGUAGE=pt
[[ ! -e /etc/texto-adm ]] && touch /etc/texto-adm
source /etc/texto-adm
if [[ -z "$(echo ${texto[$@]})" ]]; then
 retorno="$(source trans -e google -b pt:${LINGUAGE} "$@"|sed -e 's/[^a-z0-9 -]//ig' 2>/dev/null)"
 if [[ $retorno = "" ]];then
 retorno="$(source trans -e bing -b pt:${LINGUAGE} "$@"|sed -e 's/[^a-z0-9 -]//ig' 2>/dev/null)"
 fi
 if [[ $retorno = "" ]];then 
 retorno="$(source trans -e yandex -b pt:${LINGUAGE} "$@"|sed -e 's/[^a-z0-9 -]//ig' 2>/dev/null)"
 fi
echo "texto[$@]='$retorno'"  >> /etc/texto-adm
echo "$retorno"
else
echo "${texto[$@]}"
fi
}

subdom () {
SUBDOM="$1"
[[ "$SUBDOM" = "" ]] && return
randomize="$RANDOM"
    for sites in `cat $log`; do
    [[ $(echo ${DNS[@]}|grep $sites) = "" ]] && DNS+=($sites)
    [[ $(echo ${DNS[@]}|grep $sites) != "" ]] && cat $log|grep -v "$sites" > $log
    done
    while true; do
    [[ "$(pidof lynx | wc -w)" -lt "20" ]] && break
    done
    (
    HOST[$randomize]="$SUBDOM"
    curl -sSL "${HOST[$randomize]}"|grep -Eoi '<a [^>]+>'|grep -Eo 'href="[^\"]+"'|grep -Eo '(http|https)://[a-zA-Z0-9./*]+'|sort -u|awk -F "://" '{print $2}' >> $log
    ) > /dev/null 2>&1 &
}

scan_funtion () {
echo -e "\033[1;33m$(fun_trans "SCANNER DE SUBDOMINIO") \033[1;32m[NEW-ADM]"
echo -e "$barra"
#INICIA SCRIPT
unset hostcaptura
while [[ ${hostcaptura} = "" ]]; do
echo -ne "\033[1;37m $(fun_trans "Digite o dominio"): " && read hostcaptura
tput cuu1 && tput dl1
done
unset limitecaptura
while [[ ${limitecaptura} != +([0-9]) ]]; do
echo -ne "\033[1;37m $(fun_trans "Limite de captura"): " && read limitecaptura
tput cuu1 && tput dl1
done
SUB_DOM=$hostcaptura
limite=$limitecaptura
[[ ${limite} -gt "500" ]] && limite="500"
#CRIA LOG
log="./loog" && touch $log
#INICIA PRIMEIRA BUSCA
_DOM=$(curl -sSL "$SUB_DOM"|grep -Eoi '<a [^>]+>'|grep -Eo 'href="[^\"]+"'|grep -Eo '(http|https)://[a-zA-Z0-9./*]+'|sort -u|awk -F "://" '{print $2}')
  for _DOMS in `echo $_DOM`; do
 [[ $(echo ${DNS[@]}|grep ${_DOMS}) = "" ]] && DNS+=(${_DOMS})
  done
#INICIA THREADS
i=0
while true; do
DOMAIN=$(echo "${DNS[$i]}")
[[ $DOMAIN = "" ]] && break
 if [[ $(echo -e "${PESQ[@]}"|grep "$DOMAIN") = "" ]]; then
  subdom "$DOMAIN"
  echo -e " \033[1;31m(Scan\033[1;32m $((${#PESQ[@]}+1))\033[1;31m de \033[1;32m${#DNS[@]}\033[1;31m) - $(fun_trans "Escaneando") ---> \033[1;36mhttp://$DOMAIN\033[1;37m"
  PESQ+=($DOMAIN)
 fi
[[ "$(echo ${#DNS[@]})" -gt "$limite" ]] && break
i=$(($i+1))
sleep 1s
done
rm $log
echo -e "$barra\n \033[1;32m$(fun_trans "Scan Finalizado!"), $(fun_trans "Iniciando Coleta de IP")s"
[[ -e $HOME/subresult ]] && rm $HOME/subresult
[[ ! -e $HOME/subresult ]] && touch $HOME/subresult
[[ -e $HOME/result_tmp ]] && rm $HOME/result_tmp
[[ ! -e $HOME/result_tmp ]] && touch $HOME/result_tmp

for result in $(echo "${DNS[@]}"); do
(
rand="$RANDOM"
dns[rand]="$result"
scan[rand]=$(echo ${result}|cut -d'/' -f1)
IP[rand]=$(nslookup "${scan[rand]}"|grep -Eo 'Address: [0-9.]+'|grep -Eo '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}'|tail -1) > /dev/null 2>&1
echo " DNS: ${dns[rand]} -> IP: ${IP[rand]}" >> $HOME/subresult
echo -e "\033[1;31mDNS: \033[1;36m${dns[rand]} \033[1;31m--> \033[1;31mIP: \033[1;33m${IP[rand]}" >> $HOME/result_tmp
unset IP
) &
done
while true; do
[[ $(pidof nslookup|wc -w) -lt "1" ]] && break
done
RSLT=$(($(cat $HOME/subresult|wc -l)/4)) && echo -e "$barra\n \033[1;36m$RSLT $(fun_trans "Hosts Capturados")\n$barra\033[0m"
if [ $RSLT = 0 ];then 
return 0
fi
echo -ne " \033[1;33m$(fun_trans "Deseja Imprimir os Resultados?") \033[1;37m[S/N]: "; read yn
   [[ $yn = @(s|S|y|Y) ]] && {
   tput cuu1 && tput dl1
   cat $HOME/result_tmp|grep -v =
   [[ -e $HOME/result_tmp ]] && rm -rf $HOME/result_tmp
   echo -e "$barra\033[0m"
   echo -e "\033[1;32m$(fun_trans "Log Gerado no Arquivo") \033[1;33m$HOME/subresult"
   echo -e "$barra"
   return 0
   }
tput cuu1 && tput dl1
return 0
}
scan_funtion
